# Generated by Django 3.0.6 on 2020-05-19 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_number', models.IntegerField(verbose_name='Номер события')),
                ('round_number', models.IntegerField(verbose_name='Номер круга')),
                ('heat_number', models.IntegerField(verbose_name='Номер забега')),
                ('event_name', models.CharField(max_length=128, verbose_name='Название события')),
            ],
        ),
        migrations.CreateModel(
            name='EventData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Место')),
                ('_id', models.IntegerField(verbose_name='Номер участника')),
                ('edu_number', models.IntegerField(verbose_name='Номер образовательного учереждения')),
                ('edu_name', models.CharField(max_length=128, verbose_name='Название образовательного учереждения')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия участника')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя участника')),
                ('time', models.FloatField(verbose_name='Время')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='run.Event', verbose_name='Событие')),
            ],
        ),
    ]
