# Generated by Django 3.0.6 on 2020-05-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0003_auto_20200519_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_number',
            field=models.IntegerField(verbose_name='Номер события'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='number',
            field=models.CharField(max_length=8, verbose_name='Место'),
        ),
    ]
