# Generated by Django 3.0.6 on 2020-05-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0005_auto_20200519_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdata',
            old_name='_id',
            new_name='person_id',
        ),
    ]
