# Generated by Django 3.0.6 on 2020-05-24 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0006_auto_20200524_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='edu_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Название образовательного учереждения'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='edu_number',
            field=models.IntegerField(null=True, verbose_name='Номер образовательного учереждения'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='first_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Имя участника'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='last_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Фамилия участника'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='number',
            field=models.CharField(max_length=8, null=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='person_id',
            field=models.IntegerField(null=True, verbose_name='Номер участника'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='time',
            field=models.CharField(max_length=8, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='event',
            field=models.ForeignKey(default='Event', null=True, on_delete=django.db.models.deletion.CASCADE, to='run.Event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='event_number',
            field=models.IntegerField(null=True, verbose_name='Номер события'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='heat_number',
            field=models.IntegerField(null=True, verbose_name='Номер забега'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='round_number',
            field=models.IntegerField(null=True, verbose_name='Номер круга'),
        ),
    ]
