# Generated by Django 3.0.6 on 2020-05-24 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0008_auto_20200524_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=128, null=True, verbose_name='Фамилия участника')),
                ('first_name', models.CharField(max_length=128, null=True, verbose_name='Имя участника')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventdata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='eventdata',
            name='last_name',
        ),
        migrations.AddField(
            model_name='eventdata',
            name='runner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='run.Person', verbose_name='Участник'),
        ),
    ]
